import{ArrowRight,BookOpen}from"lucide-react";
import{useEffect,useState}from"react";
import{Link}from"react-router-dom";
import Container from"../../components/shared/Container.jsx";
import{blogService}from"../../services/blogService.js";
export default function InsightsPage(){
    useEffect(()=>{
        window.scrollTo(0,0);
    },[]);
    const[items,setItems]=useState([]);useEffect(()=>{document.title="Insights - LinkGhosta";blogService.listPublic().then(({data})=>setItems(data.data||[])).catch(()=>setItems([]))},[]);return <div className="-mx-4 -mb-8 bg-white"><section className="bg-ink px-4 py-16 text-white sm:py-24"><Container><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-brand-400">Insights</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-tight sm:text-6xl">Ideas for leaders who intend to be known.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Practical thinking on LinkedIn, authority, personal branding, and strategic visibility.</p></Container></section><section className="px-4 py-16 sm:py-24"><Container>{items.length?<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map(v=><article key={v._id} className="overflow-hidden rounded-lg border border-brand-500/15 bg-white shadow-[0_20px_55px_rgba(124,45,18,0.07)]">{v.coverImage?<img src={v.coverImage} alt="" className="aspect-[16/9] w-full object-cover"/>:<div className="flex aspect-[16/9] items-center justify-center bg-brand-50 text-brand-700"><BookOpen size={36}/></div>}<div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.12em] text-brand-700">{v.category} - {v.readTime} min</p><h2 className="mt-3 text-2xl font-extrabold leading-tight">{v.title}</h2><p className="mt-4 line-clamp-3 text-sm leading-7 text-neutral-600">{v.excerpt}</p><Link to={`/insights/${v.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-brand-700">Read article <ArrowRight size={16}/></Link></div></article>)}</div>:<div className="rounded-lg border border-dashed border-brand-300 bg-brand-50 p-12 text-center"><h2 className="text-2xl font-extrabold">Fresh thinking is on the way.</h2><p className="mt-3 text-neutral-600">Published articles will appear here.</p></div>}</Container></section></div>}
